name: ci
on:
  workflow_dispatch:
jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          git init
          git remote add origin "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          git fetch origin --depth=1 "$GITHUB_SHA"
          git checkout "$GITHUB_SHA"
      - run: bash ./build.sh
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="${GITHUB_SHA:0:12}"
          if gh release view "$tag" >/dev/null 2>&1; then
            gh release upload "$tag" ./bin/caddy-linux-amd64 ./bin/caddy-windows-amd64.exe --clobber
          else
            gh release create "$tag" ./bin/caddy-linux-amd64 ./bin/caddy-windows-amd64.exe --target "$GITHUB_SHA" --title "$tag" --notes "Linux and Windows x64 binaries."
          fi
